package com.rayk.health.common.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS(10101, "用户名或密码错误"),
    AUTH_UNAUTHORIZED(10102, "登录状态无效或已过期"),
    AUTH_FORBIDDEN(10103, "无权执行此操作"),
    WECHAT_LOGIN_FAILED(10201, "微信登录凭证校验失败，请重试"),
    WECHAT_NOT_CONFIGURED(10202, "微信小程序身份服务尚未配置"),
    WECHAT_ACCOUNT_NOT_BOUND(10203, "该微信账号尚未绑定系统用户"),
    WECHAT_ALREADY_BOUND(10204, "该微信账号已绑定其他系统用户"),
    WECHAT_PHONE_AUTH_FAILED(10205, "微信手机号授权校验失败，请重试"),
    PHONE_ALREADY_REGISTERED(10206, "该手机号已被系统账户使用"),
    WORKBENCH_NOT_ALLOWED(10301, "当前账号无权切换到该工作台"),
    TENANT_NOT_FOUND(10401, "机构不存在或无权访问"),
    PLATFORM_CUSTOMER_NOT_FOUND(10402, "未找到对应的客户账号"),
    DATA_COLLECTION_CONSENT_REQUIRED(10501, "请先授权健康数据采集后再继续"),
    HEALTH_ASSESSMENT_CONSENT_REQUIRED(10502, "请先授权健康评估服务后再继续"),
    DATA_SHARING_CONSENT_REQUIRED(10503, "客户尚未授权专业人员协作"),
    PATIENT_NOT_FOUND(20101, "客户不存在或无权访问"),
    LAB_REPORT_NOT_FOUND(30101, "检验报告不存在或无权访问"),
    LAB_REPORT_INVALID_STATUS(30102, "检验报告当前状态不允许此操作"),
    FILE_INVALID(30201, "仅支持真实PDF、JPG或PNG文件"),
    FILE_NOT_FOUND(30202, "报告文件不存在或无权访问"),
    FILE_STORAGE_UNAVAILABLE(30203, "文件存储服务暂时不可用"),
    OCR_TASK_NOT_FOUND(40101, "报告识别任务不存在"),
    OCR_TASK_PROCESSING(40102, "报告正在识别，请稍后再试"),
    OCR_SERVICE_UNAVAILABLE(40103, "报告识别服务暂时不可用，可稍后重新识别"),
    AI_SERVICE_UNAVAILABLE(50101, "AI服务暂时不可用"),
    VOICE_SERVICE_UNAVAILABLE(50102, "语音服务暂时不可用，请稍后再试"),
    VOICE_SERVICE_QUOTA_EXHAUSTED(50103, "语音服务当前没有可用调用额度，请联系管理员开通或充值"),
    REVIEW_INVALID_STATUS(60101, "审核任务当前状态不允许此操作"),
    FOLLOWUP_NOT_FOUND(60201, "随访任务或计划不存在或无权访问"),
    FOLLOWUP_INVALID_STATUS(60202, "随访任务或计划当前状态不允许此操作"),
    HEALTH_SCAN_NOT_CONFIGURED(60301, "健康检测服务尚未完成配置"),
    HEALTH_SCAN_NOT_FOUND(60302, "健康检测任务不存在或无权访问"),
    HEALTH_SCAN_INVALID_STATUS(60303, "健康检测任务当前状态不允许此操作"),
    HEALTH_SCAN_SERVICE_UNAVAILABLE(60304, "健康检测服务暂时不可用，请稍后重试"),
    MEMBERSHIP_BENEFIT_NOT_AVAILABLE(60401, "当前会员权益不足或已过期，请升级会员后继续"),
    MEMBERSHIP_ORDER_NOT_FOUND(60402, "会员订单不存在或无权访问"),
    MEMBERSHIP_PAYMENT_NOT_CONFIGURED(60403, "微信支付尚未完成商户配置，请联系管理员"),
    MEMBERSHIP_PAYMENT_UNAVAILABLE(60404, "微信支付服务暂时不可用，请稍后重试"),
    WECHAT_PAYMENT_SESSION_EXPIRED(60405, "微信登录状态已失效，请重新进入小程序登录后再支付"),
    MEMBERSHIP_PAYMENT_AUTH_REQUIRED(60406, "微信支付提示：商户号该产品权限未开通，请在商户平台检查后重试"),
    MEDICAL_ASSISTANT_CONVERSATION_NOT_FOUND(60501, "对话不存在或无权访问"),
    MALL_NOT_ENABLED(60600, "商城暂未开放"),
    MALL_PRODUCT_NOT_FOUND(60601, "商品不存在或已下架"),
    MALL_ADDRESS_NOT_FOUND(60602, "收货地址不存在或无权访问"),
    MALL_ORDER_NOT_FOUND(60603, "商城订单不存在或无权访问"),
    MALL_STOCK_NOT_ENOUGH(60604, "商品库存不足"),
    MALL_ORDER_INVALID_STATUS(60605, "订单当前状态不允许此操作"),
    MALL_PAYMENT_NOT_CONFIGURED(60606, "商城微信支付尚未完成小程序关联或JSAPI开通，请联系管理员"),
    MALL_PAYMENT_UNAVAILABLE(60607, "商城支付服务暂时不可用，请稍后重试"),
    MALL_PAYMENT_AUTH_REQUIRED(60608, "商城微信支付提示：商户号该产品权限未开通，请在商户平台检查后重试"),
    GOLD_BEAN_NOT_ENABLED(60700, "金豆会员功能尚未在当前环境开启"),
    GOLD_BEAN_ACCOUNT_NOT_FOUND(60701, "金豆会员账户不存在或无权访问"),
    GOLD_BEAN_REFERRAL_INVALID(60702, "推荐码无效，不能建立推荐关系"),
    GOLD_BEAN_ALREADY_REGISTERED(60703, "当前账号已完成金豆会员注册"),
    GOLD_BEAN_LEVEL_REQUIRED(60704, "当前会员等级暂不具备该权限"),
    GOLD_BEAN_REGION_CONFLICT(60705, "该城市或账号已经开辟区域"),
    GOLD_BEAN_BALANCE_INSUFFICIENT(60706, "对应金豆余额不足"),
    GOLD_BEAN_PROFIT_INVALID(60707, "区域分润金额或区域状态无效"),
    GOLD_BEAN_PAYMENT_REQUIRED(60708, "请先通过平台支付金豆会员费"),
    GOLD_BEAN_PAYMENT_NOT_CONFIGURED(60709, "金豆支付尚未完成商品配置，请联系管理员"),
    GOLD_BEAN_ORDER_NOT_FOUND(60710, "金豆订单不存在或无权访问"),
    GOLD_BEAN_ORDER_INVALID_STATUS(60711, "金豆订单当前状态不允许此操作"),
    GOLD_BEAN_PAYMENT_UNAVAILABLE(60712, "金豆支付服务暂时不可用，请稍后重试"),
    GOLD_BEAN_PLATFORM_REGISTRATION_ONLY(60713, "平台支付仅用于首个无推荐人的金豆会员注册"),
    GOLD_BEAN_PLATFORM_INVITE_REQUIRED(60714, "请填写平台发放的一次性注册授权码"),
    GOLD_BEAN_PLATFORM_INVITE_INVALID(60715, "平台注册授权码无效、已使用或已过期"),
    GOLD_BEAN_PLATFORM_INVITE_BOUND(60716, "该平台注册授权码未绑定当前手机号"),
    GOLD_BEAN_PLATFORM_INVITE_NOT_FOUND(60717, "平台注册授权码不存在或已被删除"),
    GOLD_BEAN_PLATFORM_PURCHASE_NOT_ELIGIBLE(60718, "当前会员身份不支持向平台购买金豆"),
    GOLD_BEAN_REGISTRATION_CODE_CONFLICT(60719, "一级代理只能填写平台注册码，推荐代理只能填写推荐码"),
    GOLD_BEAN_TRADE_LISTING_NOT_FOUND(60720, "金豆挂单不存在或已下架"),
    GOLD_BEAN_TRADE_LISTING_INVALID_STATUS(60721, "金豆挂单当前状态不允许此操作"),
    GOLD_BEAN_TRADE_SELF_BUY(60722, "不能购买自己发布的金豆挂单"),
    GOLD_BEAN_TRADE_LIMIT_EXCEEDED(60723, "当前可交易额度不足，不能发布这么多金豆"),
    GOLD_BEAN_TRADE_AMOUNT_INVALID(60724, "金豆交易数量无效"),
    GOLD_BEAN_TRADE_PAYMENT_NOT_CONFIGURED(60725, "金豆交易的微信支付或转账能力尚未配置"),
    GOLD_BEAN_TRADE_PAYOUT_PENDING(60726, "买家已付款，正在等待卖家收款确认"),
    GOLD_BEAN_TRADE_PAYOUT_FAILED(60727, "卖家收款失败，订单需要平台处理"),
    GOLD_BEAN_REFERRAL_PAYMENT_NOT_CONFIGURED(60728, "推荐注册的微信支付或推荐人收款能力尚未配置"),
    GOLD_BEAN_LEGENDARY_REQUIRED(60729, "当前手机号未被平台录入传奇人物资格"),
    GOLD_BEAN_LEGENDARY_NOT_FOUND(60730, "传奇人物资格记录不存在或已被删除"),
    GOLD_BEAN_LEGENDARY_PHONE_CONFLICT(60731, "该手机号已经录入传奇人物资格"),
    GOLD_BEAN_TRADE_BUCKET_INVALID(60732, "金豆出售来源无效"),
    GOLD_BEAN_REGION_DEPTH_EXCEEDED(60733, "区域推荐链最多支持三级"),
    GOLD_BEAN_REGION_PARENT_INVALID(60734, "区域上级必须来自本人直接推荐链"),
    GOLD_BEAN_TRADE_LEGENDARY_DIGITAL_ONLY(60735, "传奇人物只能购买数字银行金豆挂单"),
    GOLD_BEAN_TRADE_DIGITAL_BANK_LEGENDARY_ONLY(60736, "数字银行金豆挂单仅限传奇人物购买"),
    GOLD_BEAN_ROBOT_GROUP_NOT_CONFIGURED(60737, "机器人权益服务群二维码尚未配置，请联系管理员"),
    GOLD_BEAN_ROBOT_ALREADY_REDEEMED(60738, "机器人权益每位用户只能兑换一次"),
    HEALTH_TREE_HOLE_FEEDBACK_NOT_READY(60739, "健康树洞还未完成一个七天记录周期"),
    HEALTH_TREE_HOLE_TRIAL_EXPIRED(60740, "健康树洞七天体验已结束，请开通健康会员后继续使用"),
    GOLD_BEAN_REFERRER_BINDING_REQUIRED(60741, "推荐人尚未完成微信收款绑定，请让推荐人先用本人微信手机号登录一次"),
    GOLD_BEAN_TRADE_REGION_REQUIRED(60742, "请先完成注册区域城市后再发布或购买金豆"),
    GOLD_BEAN_TRADE_REGION_MISMATCH(60743, "普通会员只能购买本注册区域的金豆挂单"),
    GOLD_BEAN_ROBOT_BALANCE_INSUFFICIENT(60744, "数字银行金豆余额不足"),
    GOLD_BEAN_PLATFORM_PURCHASE_DISABLED(60745, "当前账号不能向平台直购金豆，请通过金豆集市购买符合条件的挂单"),
    GOLD_BEAN_TRADE_LEGENDARY_SELL_FORBIDDEN(60746, "传奇人物不能发布或出售金豆挂单"),
    INDICATOR_NOT_FOUND(70101, "指标字典项不存在或无权访问"),
    INDICATOR_CODE_DUPLICATE(70102, "指标编码已存在"),
    INDICATOR_ALIAS_DUPLICATE(70103, "指标别名已存在"),
    MODEL_CONFIG_NOT_FOUND(80101, "评估模型配置不存在"),
    MODEL_CONFIG_INVALID_STATUS(80102, "评估模型配置当前状态不允许此操作"),
    SYSTEM_VALIDATION_ERROR(90001, "请求参数校验失败"),
    SYSTEM_ERROR(99999, "系统内部错误");

    private final int code;
    private final String message;

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int code() {
        return code;
    }

    public String message() {
        return message;
    }
}
