import base64
import io
import os
import re
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, ClassVar

import httpx
from PIL import Image, ImageOps

QWEN_OCR_PROMPT = (
    "你是医疗体检报告的忠实转录引擎。\n"
    "请完整识别本页所有可见内容，尤其是检验表格和体检结论。\n"
    "严格遵守：\n"
    "1. 不得推测、补全、换算、诊断或改写原文；看不清的字段留空。\n"
    "2. 不要把姓名、性别、年龄、电话、日期、医院、科室、病区、住院号、门诊号、"
    "床位号、床号、报告号、条码号、检查号、检验号、样本号、申请单号、仪器型号、"
    "设备编号等个人或报告管理信息输出为‘指标’或‘发现’。\n"
    "3. 只要看见清晰的表格行，即使页面有检查类别标题，也必须优先逐行输出检验指标："
    "指标<TAB>项目名称<TAB>结果<TAB>单位<TAB>参考下限<TAB>参考上限<TAB>异常标记。"
    "项目名称必须取原报告可见文字，不能用‘原文’、‘项目’或‘检查结果’代替；无法确认的"
    "字段留空，不要把整行表格压成一段叙述。\n"
    "4. 对影像描述、定性结果和检查小结，逐行输出：发现<TAB>原检查类别<TAB>原项目名称<TAB>"
    "原文完整结果。类别和项目名称必须逐字采用原报告原文，禁止自行改名、合并、拆分、排序"
    "或根据项目名称猜测归类；原文完整结果必须保留数值、单位、参考范围、异常标记和文字"
    "结论，不得删减、改写或补充；同一项目不得重复输出为‘指标’。不得使用门诊号、床位号"
    "等管理字段作为检查类别或项目。\n"
    "5. 保持原始单位；参考范围只有一侧时，缺失的一侧留空。横向、倒置或旋转拍摄的页面，"
    "请先在视觉上旋转至可读方向，再按原页面顺序识别左右栏和上下区域。\n"
    "6. 除上述制表符分隔行外不要输出解释、标题、Markdown 表格或代码块。请逐项检查页面，避免漏项。"
)


class QwenOcrError(RuntimeError):
    pass


@dataclass(frozen=True)
class QwenDocument:
    lines: list[str]
    tables: list[list[list[str]]]


class _QwenHtmlParser(HTMLParser):
    """Extract visible text and table geometry from Qwen's document HTML."""

    # Qwen may return a visually faithful HTML transcription even when the prompt asks for
    # TSV.  Reports generated by different templates commonly use ``div``/``span``/``section``
    # instead of paragraphs, so only handling p/h tags silently drops imaging descriptions and
    # examination summaries.  These are text containers, not report categories; the original
    # wording is preserved and categorisation is handled by the OCR service.
    BLOCK_TAGS: ClassVar[set[str]] = {
        "p",
        "li",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "div",
        "section",
        "article",
        "header",
        "footer",
        "label",
        "dt",
        "dd",
        "caption",
        "pre",
        "blockquote",
    }

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.lines: list[str] = []
        self.tables: list[list[list[str]]] = []
        self._ignored_depth = 0
        # Keep a small block stack instead of a single active block.  Native Qwen HTML often
        # wraps every paragraph in several nested ``div`` elements; a single active block would
        # concatenate sibling paragraphs and lose the original line boundaries.
        self._blocks: list[dict[str, Any]] = []
        self._loose_parts: list[str] = []
        self._table: list[list[str]] | None = None
        self._row: list[str] | None = None
        self._cell_parts: list[str] | None = None

    @staticmethod
    def _text(parts: list[str]) -> str:
        return re.sub(r"\s+", " ", "".join(parts)).strip()

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        del attrs
        tag = tag.lower()
        if tag in {"script", "style"}:
            self._ignored_depth += 1
            return
        if self._ignored_depth:
            return
        if tag == "table":
            self._flush_loose()
            self._table = []
        elif tag == "tr" and self._table is not None:
            self._row = []
        elif tag in {"td", "th"} and self._row is not None:
            self._cell_parts = []
        elif tag in self.BLOCK_TAGS and self._table is None:
            if self._blocks:
                parent = self._blocks[-1]
                parent["has_child"] = True
                # Preserve text placed directly in a wrapper before a nested paragraph,
                # e.g. ``<div>影像表现：<p>...</p></div>``.  Without flushing here the
                # wrapper is suppressed as a duplicate and that label would be lost.
                direct = self._text(parent["parts"])
                if direct:
                    self.lines.append(direct)
                    parent["parts"] = []
            self._blocks.append({"tag": tag, "parts": [], "has_child": False})
        elif tag == "br":
            if self._cell_parts is not None:
                self._cell_parts.append(" ")
            elif self._blocks:
                self._blocks[-1]["parts"].append(" ")

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag in {"script", "style"}:
            self._ignored_depth = max(0, self._ignored_depth - 1)
            return
        if self._ignored_depth:
            return
        if tag in {"td", "th"} and self._cell_parts is not None:
            if self._row is not None:
                self._row.append(self._text(self._cell_parts))
            self._cell_parts = None
        elif tag == "tr" and self._row is not None:
            if self._table is not None and any(self._row):
                self._table.append(self._row)
            self._row = None
        elif tag == "table" and self._table is not None:
            if self._table:
                self.tables.append(self._table)
            self._table = None
        elif self._blocks and tag == self._blocks[-1]["tag"]:
            block = self._blocks.pop()
            # Leaf blocks represent the visible lines.  Wrapper blocks are suppressed to avoid
            # duplicating the same text after their child paragraphs have been emitted.
            line = self._text(block["parts"])
            if line and not block["has_child"]:
                self.lines.append(line)
            elif line and block["has_child"]:
                # Text after a nested child is also a distinct visible line.  Wrapper text
                # itself is not duplicated because direct text before the child was flushed
                # when the child started.
                self.lines.append(line)
        elif tag in {"body", "html"}:
            self._flush_loose()

    def handle_data(self, data: str) -> None:
        if self._ignored_depth:
            return
        if self._cell_parts is not None:
            self._cell_parts.append(data)
        elif self._blocks:
            self._blocks[-1]["parts"].append(data)
        elif self._table is None:
            self._loose_parts.append(data)

    def _flush_loose(self) -> None:
        if not self._loose_parts:
            return
        line = self._text(self._loose_parts)
        self._loose_parts = []
        if line:
            self.lines.append(line)


def extract_qwen_document(value: str) -> QwenDocument:
    """Accept either requested TSV text or Qwen's native HTML transcription."""

    text = value.strip()
    text = re.sub(r"^```(?:html)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
    if not re.search(
        r"<(?:html|body|table|div|section|article|p|li|h[1-6]|dt|dd|caption|label|pre|blockquote)\b",
        text,
        re.IGNORECASE,
    ):
        return QwenDocument(lines=text.splitlines(), tables=[])
    parser = _QwenHtmlParser()
    parser.feed(text)
    parser.close()
    return QwenDocument(lines=parser.lines, tables=parser.tables)


@dataclass(frozen=True)
class QwenOcrSettings:
    enabled: bool
    api_key: str
    workspace_id: str
    base_url: str
    model: str
    timeout_seconds: float
    max_pixels: int
    max_pages: int
    concurrency: int = 3
    fallback_model: str = "qwen3.5-ocr"

    @classmethod
    def from_env(cls) -> "QwenOcrSettings":
        return cls(
            enabled=os.getenv("QWEN_OCR_ENABLED", "false").strip().lower()
            in {"1", "true", "yes", "on"},
            api_key=os.getenv("QWEN_OCR_API_KEY", "").strip(),
            workspace_id=os.getenv("QWEN_OCR_WORKSPACE_ID", "").strip(),
            base_url=os.getenv("QWEN_OCR_BASE_URL", "").strip(),
            model=os.getenv("QWEN_OCR_MODEL", "qwen3.8-flash").strip(),
            timeout_seconds=float(os.getenv("QWEN_OCR_TIMEOUT_SECONDS", "180")),
            max_pixels=int(os.getenv("QWEN_OCR_MAX_PIXELS", "16000000")),
            max_pages=max(1, int(os.getenv("QWEN_OCR_MAX_PAGES", "50"))),
            concurrency=max(1, min(50, int(os.getenv("QWEN_OCR_CONCURRENCY", "3")))),
            fallback_model=os.getenv("QWEN_OCR_FALLBACK_MODEL", "qwen3.5-ocr").strip(),
        )

    @property
    def configured(self) -> bool:
        return self.enabled and bool(self.api_key)

    @property
    def compatible_base_url(self) -> str:
        if self.base_url:
            return self.base_url.rstrip("/")
        if self.workspace_id:
            return (
                f"https://{self.workspace_id}.cn-beijing.maas.aliyuncs.com"
                "/compatible-mode/v1"
            )
        return "https://dashscope.aliyuncs.com/compatible-mode/v1"

    @property
    def compatible_base_urls(self) -> list[str]:
        """Return the private workspace endpoint first and public API as fallback."""

        if self.base_url:
            return [self.base_url.rstrip("/")]
        public_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
        if not self.workspace_id:
            return [public_url]
        return [self.compatible_base_url, public_url]


@dataclass(frozen=True)
class QwenOcrPageResult:
    path: Path
    text: str | None
    model: str | None
    error: str | None = None


class QwenOcrClient:
    MAX_BASE64_BYTES = 10 * 1024 * 1024

    def __init__(
        self,
        settings: QwenOcrSettings | None = None,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        self.settings = settings or QwenOcrSettings.from_env()
        self.transport = transport

    @property
    def enabled(self) -> bool:
        return self.settings.configured

    def recognize_images(self, paths: list[Path]) -> list[str]:
        if not self.enabled:
            return []
        selected = paths[: self.settings.max_pages]
        if len(selected) <= 1 or self.settings.concurrency <= 1:
            return [self._recognize_image(path) for path in selected]
        with ThreadPoolExecutor(max_workers=self.settings.concurrency) as executor:
            return list(executor.map(self._recognize_image, selected))

    def recognize_images_best_effort(
        self, paths: list[Path], *, model: str | None = None
    ) -> list["QwenOcrPageResult"]:
        """Recognize pages independently without aborting the whole batch on one page."""

        if not self.enabled:
            return []
        selected = paths[: self.settings.max_pages]
        model_name = (model or self.settings.model).strip()

        def recognize_page(path: Path) -> QwenOcrPageResult:
            try:
                return QwenOcrPageResult(
                    path=path,
                    text=self._recognize_image(path, model=model_name),
                    model=model_name,
                )
            except (OSError, ValueError, QwenOcrError) as exc:
                # Keep the reason observable without persisting provider responses, URLs or
                # other potentially sensitive request data.
                return QwenOcrPageResult(
                    path=path,
                    text=None,
                    model=None,
                    error=f"{model_name}:{type(exc).__name__}",
                )

        if len(selected) <= 1 or self.settings.concurrency <= 1:
            return [recognize_page(path) for path in selected]
        with ThreadPoolExecutor(max_workers=self.settings.concurrency) as executor:
            return list(executor.map(recognize_page, selected))

    def _recognize_image(self, path: Path, *, model: str | None = None) -> str:
        model_name = (model or self.settings.model).strip()
        image_url = self._image_data_url(path, model_name=model_name)
        payload: dict[str, Any] = {
            "model": model_name,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {"url": image_url},
                            "max_pixels": self.settings.max_pixels,
                        },
                        {"type": "text", "text": QWEN_OCR_PROMPT},
                    ],
                }
            ],
            "temperature": 0,
            "max_tokens": 16384,
        }
        last_error: Exception | None = None
        body: dict[str, Any] | None = None
        with httpx.Client(
            timeout=self.settings.timeout_seconds,
            transport=self.transport,
        ) as client:
            for base_url in self.settings.compatible_base_urls:
                endpoint = f"{base_url}/chat/completions"
                try:
                    response = client.post(
                        endpoint,
                        headers={
                            "Authorization": f"Bearer {self.settings.api_key}",
                            "Content-Type": "application/json",
                        },
                        json=payload,
                    )
                    response.raise_for_status()
                    body = response.json()
                    break
                except (httpx.HTTPError, ValueError) as exc:
                    last_error = exc
        if body is None:
            raise QwenOcrError(f"{model_name} request failed") from last_error
        try:
            content = body["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise QwenOcrError(f"{model_name} returned an invalid response") from exc
        if isinstance(content, list):
            content = "\n".join(
                str(item.get("text", "")) if isinstance(item, dict) else str(item)
                for item in content
            )
        result = str(content).strip()
        if not result:
            raise QwenOcrError(f"{model_name} returned no text")
        return result

    def _image_data_url(self, path: Path, *, model_name: str | None = None) -> str:
        with Image.open(path) as source:
            image = ImageOps.exif_transpose(source).convert("RGB")
            longest = max(image.size)
            if longest > 5200:
                image.thumbnail((5200, 5200), Image.Resampling.LANCZOS)
            quality = 94
            while True:
                buffer = io.BytesIO()
                image.save(buffer, format="JPEG", quality=quality, optimize=True)
                encoded = base64.b64encode(buffer.getvalue())
                if len(encoded) <= self.MAX_BASE64_BYTES or quality <= 68:
                    break
                quality -= 6
            if len(encoded) > self.MAX_BASE64_BYTES:
                raise QwenOcrError(
                    f"Image is too large for {model_name or self.settings.model} Base64 input"
                )
        return "data:image/jpeg;base64," + encoded.decode("ascii")
