-- Formal model: platform admin, doctor and customer only. Follow-up is generated by Rayk AI.
ALTER TABLE health_patient
  ADD COLUMN phone_hash CHAR(64) NULL COMMENT 'SHA-256 normalized phone for authorised doctor search' AFTER phone_masked;
CREATE INDEX idx_health_patient_phone_hash ON health_patient (tenant_id, phone_hash);
UPDATE health_patient p
JOIN sys_user u ON u.id = p.user_id AND u.deleted = 0
SET p.phone_hash = u.phone_hash
WHERE p.phone_hash IS NULL;

-- Retire the institution-admin and health-manager accounts/workbenches without deleting historical records.
UPDATE sys_user_workbench SET deleted = 1
WHERE workbench_code IN ('TENANT_ADMIN', 'HEALTH_MANAGER') AND deleted = 0;
UPDATE sys_user_role ur
JOIN sys_role r ON r.id = ur.role_id
SET ur.deleted = 1
WHERE r.role_code IN ('TENANT_ADMIN', 'HEALTH_MANAGER') AND ur.deleted = 0;
UPDATE sys_role SET status = 'DISABLED', deleted = 1
WHERE role_code IN ('TENANT_ADMIN', 'HEALTH_MANAGER') AND deleted = 0;

-- Doctors are read-only hospital viewers; remove old approval and publication permissions.
UPDATE sys_role_permission rp
JOIN sys_role r ON r.id = rp.role_id AND r.deleted = 0
JOIN sys_permission p ON p.id = rp.permission_id AND p.deleted = 0
SET rp.deleted = 1
WHERE r.role_code = 'DOCTOR'
  AND p.permission_code IN ('assessment:review', 'report:publish', 'followup:manage', 'followup:create', 'patient:create');
UPDATE sys_user_role customer_role
JOIN sys_role customer ON customer.id = customer_role.role_id AND customer.role_code = 'CUSTOMER'
JOIN sys_user_role doctor_role ON doctor_role.user_id = customer_role.user_id AND doctor_role.deleted = 0
JOIN sys_role doctor ON doctor.id = doctor_role.role_id AND doctor.role_code = 'DOCTOR'
SET customer_role.deleted = 1
WHERE customer_role.deleted = 0;
UPDATE sys_user_workbench w
JOIN sys_user_role doctor_role ON doctor_role.user_id = w.user_id AND doctor_role.deleted = 0
JOIN sys_role doctor ON doctor.id = doctor_role.role_id AND doctor.role_code = 'DOCTOR'
SET w.deleted = 1
WHERE w.workbench_code = 'CUSTOMER' AND w.deleted = 0;
INSERT IGNORE INTO sys_role_permission
  (id, tenant_id, role_id, permission_id, created_by, created_at, updated_by, updated_at, deleted, version)
SELECT r.id * 100000 + 12002, r.tenant_id, r.id, 12002, 1, NOW(), 1, NOW(), 0, 0
FROM sys_role r WHERE r.role_code = 'DOCTOR' AND r.deleted = 0;
INSERT IGNORE INTO sys_role_permission
  (id, tenant_id, role_id, permission_id, created_by, created_at, updated_by, updated_at, deleted, version)
SELECT r.id * 100000 + 12012, r.tenant_id, r.id, 12012, 1, NOW(), 1, NOW(), 0, 0
FROM sys_role r WHERE r.role_code = 'DOCTOR' AND r.deleted = 0;

-- Existing customers should no longer retain a health-manager assignment.
UPDATE health_patient SET assigned_manager_id = NULL WHERE assigned_manager_id IS NOT NULL;
