CREATE TABLE health_scan_task (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    out_user_id VARCHAR(64) NOT NULL,
    vendor_detect_id VARCHAR(128) NULL,
    status VARCHAR(24) NOT NULL,
    environment VARCHAR(16) NOT NULL,
    plugin_version VARCHAR(64) NULL,
    video_digest VARCHAR(32) NULL,
    vendor_code VARCHAR(64) NULL,
    vendor_message VARCHAR(500) NULL,
    heart_rate DECIMAL(10, 2) NULL,
    heart_rate_variability DECIMAL(10, 2) NULL,
    oxygen_saturation DECIMAL(10, 2) NULL,
    respiration_rate DECIMAL(10, 2) NULL,
    systolic_blood_pressure DECIMAL(10, 2) NULL,
    diastolic_blood_pressure DECIMAL(10, 2) NULL,
    stress_hrv DECIMAL(10, 2) NULL,
    quality_score DECIMAL(10, 2) NULL,
    raw_result_json LONGTEXT NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_health_scan_user_time (tenant_id, user_id, created_at),
    KEY idx_health_scan_patient_time (tenant_id, patient_id, created_at),
    KEY idx_health_scan_status (status, updated_at),
    UNIQUE KEY uk_health_scan_out_user (out_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

