CREATE TABLE IF NOT EXISTS gold_member_order (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    order_no VARCHAR(80) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    amount_cent INT NOT NULL,
    gold_bean_quantity BIGINT NOT NULL DEFAULT 0,
    registration_referral_code VARCHAR(64) NULL,
    registration_city VARCHAR(64) NULL,
    registration_fee_recipient VARCHAR(16) NOT NULL DEFAULT 'PLATFORM',
    product_id VARCHAR(128) NOT NULL,
    payment_channel VARCHAR(32) NULL,
    transaction_id VARCHAR(128) NULL,
    payment_notify_at DATETIME NULL,
    paid_at DATETIME NULL,
    expires_at DATETIME NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_gold_member_order_no (order_no),
    UNIQUE KEY uk_gold_member_order_transaction (transaction_id),
    KEY idx_gold_member_order_customer (tenant_id, customer_id, status, created_at),
    KEY idx_gold_member_order_type (tenant_id, order_type, created_at)
);
